{ pkgs
, lib ? pkgs.lib
, kernelFile ? "/Image"
, dtbFile ? "/ax630c-nanokvm-pro.dtb"
, label ? "NixOS appliance, mainline" # informational; not a MENU keyword
, # The NixOS generation this entry boots, as an `init=` token. Empty means
  # "no init= at all", which is what the flake's baked payload ships: stage 1
  # then falls back to its built-in `/init`, the symlink to the system
  # profile, and a generation switch takes effect with no boot-chain write.
  #
  # THE INSTALLER PINS IT (#89 rung 5). `nanokvm-install-boot` writes this
  # file with `init=<toplevel>/init` for the generation being installed, and
  # `nanokvm-mark-good` copies the file that booted a healthy system to
  # `extlinux-fallback.conf`. That is the whole of the rollback: two configs
  # naming two generations, and a boot counter that picks the second one.
  # With the profile symlink in both, both entries would boot the same
  # userspace and `altbootcmd` would be a no-op.
  init ? ""
, # WHICH KERNEL THIS ENTRY BOOTS, ON THE COMMAND LINE (#86). `sysboot` loads
  # LINUX and FDT and then tells the kernel nothing about which files they were,
  # so a running system cannot otherwise know whether U-Boot took
  # extlinux.conf or extlinux-fallback.conf, nor which `/boot/Image-<hash>` it
  # read. `nanokvm-mark-good` needs exactly that to promote the (generation,
  # kernel) PAIR that booted healthy -- it reads this token out of /proc/cmdline.
  # No dot in the name, so the kernel hands it to init as an environment
  # variable instead of trying to resolve it as a module parameter.
  bootId ? ""
, extraAppend ? ""
, ...
}:

# ===========================================================================
# /boot/extlinux/extlinux.conf -- the boot payload description mainline U-Boot
# reads (#89 rung 3).
#
# `bootcmd` runs `sysboot mmc 0:10 any ${scriptaddr} /extlinux/extlinux.conf`;
# `bootmeth_extlinux` parses this file, loads LINUX and FDT off the same FAT32
# partition, and sets `bootargs` from APPEND before `booti`. That is the whole
# of the handover: nothing here comes from the U-Boot environment, and the
# kernel and device tree no longer live in signed partitions loaded by byte
# offset the way the vendor chain loaded them.
#
# THE COMMAND LINE is the one hardware-proven in rung 2q round 6, minus that
# round's two test-only tokens:
#
#   * `watchdog.open_timeout=` is a DEADMAN, not a setting. Nothing in the
#     appliance opens /dev/watchdog, so the watchdog core pets U-Boot's dog
#     from kernel context forever; with an open deadline it stops, and a
#     perfectly healthy board resets a few minutes in. It belongs on a boot
#     you are watching, never on a shipped one.
#   * `systemd.mask=systemd-pstore.service` keeps a boot's ramoops readable by
#     stopping systemd from archiving and unlinking it (which zaps the live
#     console zone). Also a harness setting.
#
# `mem=512M` STAYS for now. The board has 1 GiB and the appliance sees 428 MB
# usable; dropping it made the kernel die before any console in rung 2p, and
# what lives above 512 MB has not been established. Owned by a later rung.
#
# `blkdevparts=` is the layout, and it is the same string U-Boot's own
# `part_cmdline` driver reads -- nixos/emmc-partitions.nix parses it out of
# dts/ax630c-nanokvm-pro.dts, so there is one definition, not three.
# ===========================================================================

let
  layout = import ../nixos/emmc-partitions.nix { inherit lib; };

  append = lib.concatStringsSep " " ([
    "mem=512M"
    "console=ttyS0,115200n8"
    "earlycon=uart8250,mmio32,0x4880000"
    "board_id=0x5,boot_reason=0x00,initcall_debug=0"
    "loglevel=8"
    "usbcore.autosuspend=-1"
    "root=${layout.root.device}"
    "rootfstype=ext4"
    "rw"
    "rootwait"
    layout.blkdevparts
    "logomode=vo0@dsi_dpi_video"
    # NixOS stage 1's fail() is INTERACTIVE: without this it blocks on `read`
    # from a console whose pads nobody can reach, and the board looks hung.
    #
    # THE TOKEN HAS NO `=1`, AND THAT IS THE WHOLE POINT. Upstream's parser is
    # `case $o in boot.panic_on_fail|stage1panic=1)`, and a shell `case`
    # pattern must match the WHOLE word -- so `boot.panic_on_fail=1`, which is
    # what this line said until 2026-09-09, matches NOTHING and silently leaves
    # `panicOnFail` unset. It cost the rung-5 drill and a bench trip: a
    # generation whose stage 1 failed sat in `read -n 1 reply` forever instead
    # of panicking, so the board never reset and `bootcount` never counted.
    # `nixos/appliance.nix` now also sets `panicOnFail=1` from
    # `preDeviceCommands`, which does not depend on this string at all.
    "boot.panic_on_fail"
    "stage1panic=1"
    "panic=10"
  ] ++ lib.optional (bootId != "") "nanokvmboot=${bootId}"
    ++ lib.optional (init != "") "init=${init}"
    ++ lib.optional (extraAppend != "") extraAppend);
in
''
  # NanoKVM-Pro -- mainline boot chain (#89). Generated by pkgs/extlinux.nix.
  #
  # NO `MENU` KEYWORD ANYWHERE, and that is load-bearing on this board.
  # `boot/pxe_utils.c` does `case T_MENU: cfg->prompt = 1;` -- ANY `MENU`
  # line, `MENU TITLE` and `MENU LABEL` included, makes the whole config
  # interactive. `menu_get_choice()` then takes `menu_interactive_choice()`,
  # which calls `cli_readline_into_buffer("Enter choice: ", ...)` and reads
  # the console. This board's console is a hidden, unterminated UART pad: a
  # character of line noise is an unmatched key, and the loop prints
  # "<junk> not found" and asks again, forever, with the timeout reset each
  # time. Without a `MENU` line `cfg->prompt` stays 0, `menu_default_choice()`
  # picks DEFAULT, and nothing reads the console at all.
  #
  # The human-readable label (${label}) therefore rides in this comment and
  # nowhere else. GENERATIONS ARE NOT LABELS HERE EITHER, for the same reason:
  # `sysboot` boots DEFAULT and has no way to name a label, so the choice
  # between "this generation" and "the last one that worked" is made by
  # choosing a FILE -- extlinux.conf or extlinux-fallback.conf -- which is
  # what `bootcmd` and `altbootcmd` do.
  DEFAULT nixos
  TIMEOUT 10

  LABEL nixos
  	LINUX ${kernelFile}
  	FDT ${dtbFile}
  	APPEND ${append}
''
