{ pkgs, boot, envSize ? 1048576, ... }:

# ===========================================================================
# The U-Boot environment partition image (p7 `env`, 1 MiB), from source.
#
# THE VENDOR .axp SHIPS NO ENVIRONMENT AT ALL. Its only env-related manifest
# entry is an `ERASEENV` action with `select="0"`, and the SDK's XML generator
# skips `env` when it emits image nodes. A stock flash therefore ERASES p7 and
# lets the board repopulate it: U-Boot's own download engine writes `bootargs`
# after the repartition step, and `set_slot_ab` / `update_cmdline` write the
# rest on the first boot. That is a perfectly good scheme, and it is also why
# `.#firmware-image` has never carried an environment.
#
# We ship one anyway, because an image whose every stored partition is built
# from source should not have a partition whose content is "whatever the
# bootloader felt like writing". The content is derived, not invented:
#
#   bootdelay=0        THE COMPILED-IN DEFAULT ENVIRONMENT, and all of it.
#   baudrate=115200    `default_environment[]` gets `bootdelay` from
#                      CONFIG_BOOTDELAY (Axera changed the Kconfig default from
#                      2 to 0 -- the reason this board has no autoboot
#                      interrupt window) and `baudrate` from CONFIG_BAUDRATE.
#                      The board sets neither CONFIG_USE_BOOTARGS nor
#                      CONFIG_BOOTCOMMAND, so there is no default bootcmd and
#                      no default bootargs. Read them out of the binary:
#                        strings u-boot.bin | grep -A1 '^bootdelay=0$'
#
#   bootargs=...       LIFTED VERBATIM FROM THE U-BOOT WE BUILD (below). The
#                      kernel command line is a compiled-in string
#                      (`KERNEL_BOOTARGS`, generated by the SDK build from
#                      partition_ab.mak), not an environment default -- so the
#                      one place it can be read from without hand-copying is
#                      our own u-boot.bin. It carries `root=/dev/mmcblk0p17`
#                      and the whole `blkdevparts=mmcblk0:` clause, i.e. the
#                      same partition table nixos/emmc-partitions.nix parses
#                      out of dts/ax630c-nanokvm-pro.dts.
#
#   bootsystem=A       The A/B slot U-Boot booted from. It is an OUTPUT, not an
#                      input: `set_slot_ab()` reads the slot register and
#                      writes this variable on every boot. `A` is what a cold
#                      boot produces, and it is what `nanokvm-checkboot.service`
#                      reads back with fw_printenv on the very first boot.
#
# U-Boot rewrites parts of this on every boot regardless -- `board_id` and
# `boot_reason` digits are patched into `bootargs` in place, `mem=` is
# re-derived from /boot/configs and the board id, `bootcmd` is forced by the
# boot-mode dispatcher, and ` logomode=vo0@dsi_dpi_video` is appended once if
# the logo renders. None of that is ours to predict, and none of it has to be:
# a wrong or missing variable here self-heals, because `get_part_info()` falls
# back to the compiled-in BOOTARGS_EMMC whenever the environment's bootargs is
# absent or has no `blkdevparts`, and a bad CRC just loads the default
# environment. An all-zero env partition boots this board to slot A.
#
# WHERE IT GOES. `CONFIG_ENV_IS_IN_MMC=y`, `CONFIG_SYS_MMC_ENV_DEV 0`,
# `CONFIG_SYS_MMC_ENV_PART 0` -- the eMMC user area, at the `env` partition's
# offset, a single copy (no `CONFIG_SYS_REDUNDAND_ENVIRONMENT`, so the image is
# a 4-byte CRC32 followed by the NUL-separated variables, with no flag byte).
# nixos/emmc-partitions.nix computes that offset (0x4C0000) and size (0x100000)
# from the `blkdevparts=` clause, and #78 confirmed both ON HARDWARE: the
# appliance's `fw_printenv -n bootsystem` read `B` out of the live environment
# there, which it could not have done had either number or the CRC layout been
# wrong.
# ===========================================================================

pkgs.runCommand "nanokvm-uboot-env.bin"
{
  nativeBuildInputs = [ pkgs.ubootTools pkgs.binutils pkgs.python3 ];
  meta.description = "NanoKVM-Pro U-Boot environment partition image (${toString (envSize / 1024)} KiB)";
} ''
  ub=${boot}/images/u-boot.bin
  cp ${./uboot-env.txt} env.txt
  chmod u+w env.txt

  # ---- the committed text must BE U-Boot's own default environment --------
  # Every variable in the file except `bootsystem` (written at runtime, so it
  # is not in default_environment[]) must appear verbatim in the U-Boot binary
  # this flake builds. A defconfig change that alters the default environment
  # therefore fails the build rather than silently shipping an environment the
  # bootloader never had.
  while IFS= read -r line; do
    case "$line" in ""|"#"*|bootsystem=*) continue ;; esac
    if ! grep -qaF "$line" "$ub"; then
      echo "ERROR: '$line' is not in U-Boot's compiled-in default environment." >&2
      echo "       pkgs/uboot-env.txt has drifted from $ub" >&2
      exit 1
    fi
    echo "  default env: $line"
  done < env.txt

  # ---- bootargs, lifted out of the binary rather than transcribed ---------
  strings -n 32 "$ub" | grep -E '^mem=[0-9]+M .*root=/dev/mmcblk0p[0-9]+ .*blkdevparts=mmcblk0:' \
    | sort -u > bootargs.candidates
  n=$(wc -l < bootargs.candidates)
  if [ "$n" != 1 ]; then
    echo "ERROR: expected exactly one KERNEL_BOOTARGS string in $ub, found $n:" >&2
    cat bootargs.candidates >&2
    exit 1
  fi
  bootargs=$(cat bootargs.candidates)
  echo "  compiled-in bootargs: $bootargs"

  # The three tokens U-Boot patches in place on every boot must be present, or
  # update_cmdline() bails out early and the kernel sees a stale board id.
  for tok in 'board_id=0x0' 'boot_reason=0x00' 'mem='; do
    case "$bootargs" in
      *"$tok"*) ;;
      *) echo "ERROR: compiled-in bootargs has no '$tok'" >&2; exit 1 ;;
    esac
  done
  # ...and it must name the root partition nixos/emmc-partitions.nix derived.
  case "$bootargs" in
    *"root=/dev/mmcblk0p17 "*) ;;
    *) echo "ERROR: compiled-in bootargs does not boot p17" >&2; exit 1 ;;
  esac

  printf 'bootargs=%s\n' "$bootargs" >> env.txt

  mkenvimage -s ${toString envSize} -o env.bin env.txt
  size=$(stat -c %s env.bin)
  [ "$size" = "${toString envSize}" ] \
    || { echo "ERROR: env image is $size B, expected ${toString envSize}" >&2; exit 1; }

  # ---- round-trip: parse it back exactly as U-Boot's env_import does -----
  # crc32 over everything after the 4-byte header, compared with the header,
  # then the NUL-separated variables. This is the check that decides whether
  # the board gets this environment or silently falls back to the compiled-in
  # default, so it is worth making here rather than discovering on a board
  # with no console.
  #
  # (Not `fw_printenv`: pointed at a regular file it spins forever. On the
  # appliance it reads /dev/mmcblk0 at the partition offset and is fine.)
  python3 ${./uboot-env-verify.py} env.bin env.txt

  install -Dm444 env.bin "$out"
''
