{ pkgs, crossPkgs, uboot-mainline, ... }:

# ===========================================================================
# Hardware-free gate for the mainline U-Boot port (#89 rung 0).
#
#   nix build .#checks.x86_64-linux.uboot-mainline -L
#
# Four assertions, in the order a bad change breaks them:
#
#   1. It links at 0x5C000400. The first-stage loader jumps to that address
#      as a compile-time constant and the 1 KiB image header carries no load
#      address, so a relink is a board that never prints anything.
#   2. The signed image carries the AX boot header magic 0x55543322 and fits
#      the `uboot` partition. The vendor sign tool exits 0 on overflow and
#      writes nothing, which is exactly the failure that would otherwise be
#      discovered on a bricked board.
#   3. The device tree inside the image is the board's, and reserves the four
#      regions that belong to somebody else.
#   4. The blkdevparts= partition driver, COMPILED FROM THE SHIPPED SOURCE,
#      parses the clause in dts/ax630c-nanokvm-pro.dts into exactly the
#      partitions nixos/emmc-partitions.nix computes from the same string --
#      including p16 = boot and p17 = rootfs at the right byte offsets. Two
#      independent parsers, one source of truth.
# ===========================================================================

let
  inherit (pkgs) lib;

  layout = uboot-mainline.passthru.layout;
  crossPrefix = crossPkgs.stdenv.cc.targetPrefix;

  # A device big enough that the trailing `-(rootfs)` has room: the last fixed
  # offset plus a gigabyte. The real eMMC is 32 GB; only the arithmetic matters.
  deviceBytes = layout.root.offset + 1073741824;

  expectedH = pkgs.writeText "expected.h" ''
    /* Generated by pkgs/uboot-mainline-check.nix from nixos/emmc-partitions.nix. */
    #define EXPECTED_COUNT		${toString (lib.length layout.parts)}
    #define EXPECTED_BOOT_PART	${toString layout.bootfs.number}
    #define EXPECTED_ROOT_PART	${toString layout.root.number}
    #define EXPECTED_DEVICE_BYTES	${toString deviceBytes}ULL

    struct expected_part {
    	const char *name;
    	unsigned long long offset;
    	unsigned long long size;	/* 0 = to the end of the device */
    };

    static const struct expected_part expected_parts[] = {
    ${lib.concatMapStrings (p: ''
      	{ "${p.name}", ${toString p.offset}ULL, ${toString (if p.size == null then 0 else p.size)}ULL },
    '') layout.parts}};
  '';
in

pkgs.runCommand "uboot-mainline-check"
  {
    nativeBuildInputs = [
      pkgs.stdenv.cc
      crossPkgs.buildPackages.binutils
    ];
    meta.platforms = [ "x86_64-linux" ];
  }
  ''
    set -euo pipefail
    ub=${uboot-mainline}

    echo "=== 1. link address ==="
    entry=$(${crossPrefix}readelf -h "$ub/images/u-boot.elf" | awk '/Entry point/ { print $NF }')
    echo "entry point: $entry"
    test "$entry" = "${lib.toLower uboot-mainline.passthru.textBase}" \
      || { echo "ERROR: entry $entry != ${uboot-mainline.passthru.textBase}" >&2; exit 1; }

    echo "=== 2. signed image ==="
    img="$ub/images/u-boot_mainline_signed.bin"
    magic=$(od -An -tx1 -j4 -N4 "$img" | tr -d ' ')
    echo "header magic: $magic"
    test "$magic" = "22335455" \
      || { echo "ERROR: bad AX header magic $magic" >&2; exit 1; }
    sz=$(stat -c %s "$img")
    raw=$(stat -c %s "$ub/images/u-boot.bin")
    echo "signed: $sz bytes (raw $raw), partition ${toString uboot-mainline.passthru.ubootPartSize} bytes"
    test "$sz" -le ${toString uboot-mainline.passthru.ubootPartSize} \
      || { echo "ERROR: signed image does not fit the uboot partition" >&2; exit 1; }

    echo "=== 3. device tree ==="
    ${pkgs.dtc}/bin/fdtdump "$ub/images/u-boot.dtb" > dt.txt 2>/dev/null
    for want in '"sipeed,nanokvm-pro"' 'ddr-retrain@40000000' 'atf@40040000' \
                'optee@44200000' 'pstore@48000000' 'serial@4880000' 'mmc@1b40000'; do
      grep -qF "$want" dt.txt \
        || { echo "ERROR: $want missing from the U-Boot device tree" >&2; exit 1; }
    done
    echo "model, the four reservations, the console and the eMMC are all present"

    echo "=== 4. blkdevparts= parser ==="
    mkdir -p t
    cp "$ub/src/part_cmdline.c" t/
    cp ${expectedH} t/expected.h
    cp ${./uboot-mainline/tests/part-cmdline-test.c} t/part-cmdline-test.c

    cc -O1 -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare \
       -I ${./uboot-mainline/tests/include} -I t \
       -DCONFIG_CMDLINE_PARTITION_MAX=32 \
       -DCONFIG_CMDLINE_PARTITION_DEFAULT='"${layout.blkdevparts}"' \
       -o t/part-cmdline-test t/part-cmdline-test.c
    ./t/part-cmdline-test

    echo "=== 5. default environment ==="
    # The layout injection has to reach the linked image, not just the
    # defconfig: bootpart is what `sysboot` addresses, and the milestone
    # register is the board's only pre-Linux evidence channel.
    #
    # The four milestone values are asserted literally because they are a
    # PARTITIONING of a register Linux also writes: bits 12..27 belong to the
    # bring-up initramfs (#75-#82) and the appliance self-test (#78), and a
    # bootloader bit that drifted down into that range would silently forge
    # somebody else's evidence rather than fail.
    # bootpart is HEXADECIMAL: every U-Boot command that takes a `dev:part`
    # string parses the partition with base 16, so p16 is `mmc 0:10`. Getting
    # this wrong is not a build error -- the board reports
    # "** Invalid partition 22 **" and resets (measured 2026-09-08).
    for want in 'bootpart=${lib.toLower (lib.toHexString layout.bootfs.number)}' 'bootlimit=3' \
                'msreg_set=0x02390028' 'preboot=mw.l' 'altbootcmd=mw.l' \
                'ms_uboot=0x10000000' 'ms_extlinux=0x20000000' \
                'ms_altboot=0x40000000' 'ms_failed=0x80000000'; do
      grep -qa "$want" "$ub/images/u-boot.bin" \
        || { echo "ERROR: \"$want\" missing from the built-in environment" >&2; exit 1; }
    done
    ! grep -qa 'ms_[a-z]*=0x0[0-9a-f]' "$ub/images/u-boot.bin" \
      || { echo "ERROR: a milestone bit below 28 is set; 12..27 belong to Linux" >&2; exit 1; }
    echo "bootpart, bootlimit, altbootcmd and the four milestone bits (28..31) are all built in"

    mkdir -p "$out"
    { echo "u-boot: ${uboot-mainline.version}, entry $entry"
      echo "signed: $sz bytes of ${toString uboot-mainline.passthru.ubootPartSize}"
      echo "layout: ${layout.blkdevparts}"
    } > "$out/report"
    cat "$out/report"
  ''
