/*
 * kvm_capture_geom.h -- parametric geometry for the BLOB-FREE capture backend.
 *
 * The open capture backend (kvm_capture_open.c) drives the /dev/ax_* char
 * devices with byte-replayed selector payloads captured off the vendor path
 * (docs/blob-replacement.md, Stages 5-6). Five of those payloads carry the
 * frame geometry; this module owns them, so a non-1080p HDMI source can be
 * driven without editing captured byte arrays by hand (issue #17).
 *
 * NOTHING ELSE about the payloads is derived or invented: the templates are the
 * captured 1080p bytes verbatim, and only the geometry words identified below
 * are overwritten. At 1920x1080 every generated byte, descriptor word and pool
 * size is BIT-IDENTICAL to the pre-parameterization constants -- proven
 * mechanically by tests/geom_identity_test.c against arrays extracted from the
 * pre-change source (nix build .#checks.<system>.open-capture-geometry).
 *
 * This header is deliberately free of any Axera SDK dependency so the geometry
 * math can be compiled and tested on the build host.
 */
#ifndef KVM_CAPTURE_GEOM_H
#define KVM_CAPTURE_GEOM_H

#include <stdint.h>

/* copy_from_user sizes of the geometry-bearing selectors (from the ax_proton.ko
 * leaf-handler disassembly -- docs/blob-replacement.md Stage 5/6 tables). */
#define KVM_GEOM_DEV_ATTR_LEN 376  /* proton nr17 CreateDev / nr21 SetDevAttr  */
#define KVM_GEOM_PIPE_LEN      76  /* proton nr35 CreatePipe / nr42 SetPipeAttr */
#define KVM_GEOM_CHN_LEN       48  /* proton nr48 SetChnAttr                    */

/* VB pool floorplan (pool nr22 AX_POOL_SetConfig). BlkCnt/MetaSize are the
 * captured vendor values and do NOT scale with geometry; only BlkSize does. */
#define KVM_POOL_BLKCNT_OPEN 4     /* blocks in the common pool (== Stage-6)   */
#define KVM_POOL_METASIZE    4096  /* per-block metadata page (nr22 @0x28)     */

/* Bytes per pixel on the wire and in the pool: VIN ISP-bypass emits
 * YUV422 interleaved YUYV, 2 B/px (device-verified end-to-end, Stage 6). */
#define KVM_GEOM_BPP 2

/* Supported geometry envelope -- see kvm_geom_check() for the reasoning. */
#define KVM_GEOM_MIN_W    64
#define KVM_GEOM_MIN_H    64
#define KVM_GEOM_MAX_W    1920
#define KVM_GEOM_MAX_H    1200
#define KVM_GEOM_W_ALIGN  2   /* hard: one YUYV macropixel is 2 px            */
#define KVM_GEOM_H_ALIGN  2   /* hard: progressive frame, 2-line chroma pair  */

/* Line-stride alignment, in PIXELS (x2 for bytes). ASSUMPTION -- the RE record
 * never captured a non-1080p bring-up, so no measured alignment rule exists.
 * 16 px = 32 B is the AX DMA/VENC habit (VENC macroblocks are 16 px; AX buffer
 * helpers align strides to 32 B) and is a NO-OP for every standard HDMI width
 * we can receive except 1366 (-> 1376). Padding up can only ever make the pool
 * block larger than the hardware needs; an under-aligned stride could make the
 * VIN DMA round up internally and write past the end of a block. */
#define KVM_GEOM_STRIDE_ALIGN 16

/* Everything a bring-up needs that depends on {w,h}. */
typedef struct {
    int      w, h;        /* validated source geometry, pixels               */
    int      stride;      /* line stride in PIXELS (>= w, see STRIDE_ALIGN)  */

    /* Selector payloads, ready to hand to ioctl (captured template + geometry) */
    unsigned char dev_attr [KVM_GEOM_DEV_ATTR_LEN]; /* nr17 CreateDev + nr21   */
    unsigned char dev_attr2[KVM_GEOM_DEV_ATTR_LEN]; /* nr21 SetDevAttr #2      */
    unsigned char pipe_create[KVM_GEOM_PIPE_LEN];   /* nr35 CreatePipe         */
    unsigned char pipe_attr  [KVM_GEOM_PIPE_LEN];   /* nr42 SetPipeAttr        */
    unsigned char chn_attr   [KVM_GEOM_CHN_LEN];    /* nr48 SetChnAttr         */

    /* os_mem nr1 allocator descriptor words 0/1 ({width,height}; the ONLY
     * genuine pointer arg on the capture path -- docs/blob-replacement.md). */
    uint32_t osmem_desc[2];

    /* pool nr22 floorplan + the derived pool layout kvm_cap_get needs. */
    uint32_t blk_size;    /* AX_POOL_CONFIG_T.BlkSize @0x30                   */
    uint32_t blk_pitch;   /* page-aligned per-block pitch inside comm_pool_0  */
    uint64_t pool_span;   /* meta pages + all block pitches (bounds check)    */
} kvm_geom;

/* Validate a source geometry. Returns 0 if the open backend can drive it, -1
 * otherwise; *why (if non-NULL) gets a static human-readable reason. */
int kvm_geom_check(int w, int h, const char **why);

/* Build every geometry-dependent payload/value for (w,h). Returns 0 on
 * success, -1 (leaving *g zeroed) if kvm_geom_check() rejects the geometry. */
int kvm_geom_build(kvm_geom *g, int w, int h);

#endif /* KVM_CAPTURE_GEOM_H */
