/* SPDX-License-Identifier: GPL-2.0 OR MIT */
/* AUTO-GENERATED by pkgs/vcenc-ewl/tests/gen_vectors.py -- do not edit.
 *
 * VC8000E QP-dependent register tables, mined from the decoded VENDOR
 * register programs under docs/reference/vcenc-open/ (17-geometry probe
 * 2026-08-31 + vendor differential campaign 2026-09-04).  Laws:
 *
 *   sw7        = (pic_init_qp << 26) | (frame_qp << 8)
 *   sw125+k    = F_<type>(q - 2k), k = 0..7
 *   sw37       = L(q)
 *   q          = min(QP,35)      for I frames
 *   q          = min(QP,35) - 3  for P frames
 *
 * F is a per-frame-type LUT: the I and P instantiations are identical at
 * every commonly observed index EXCEPT q=19 (hi16 0x0200 vs 0x0204) and
 * q=20 (lo16 0x0800 vs 0x0810), so the two tables are kept separate and each
 * is derived only from programs of its own frame type.  L is a single table:
 * the I (q) and P (q) observations cross-validate at q=19 and q=22.
 *
 * Per-entry provenance is in the trailing comment: `obs <file>` = read
 * straight out of that vendor program; `derived` = filled from the
 * L(q) = (floor4(F_I(2q-48).hi * 2/3) << 16) | F_I(2q-48).lo relation, which
 * reproduces every observed (L, F) pair exactly; `interpolated` = no
 * observation, geometric fit between the neighbours (F ~ 2^(q/6),
 * lambda ~ 2^(q/3)) rounded to the LUT's own field granularity.
 */
#ifndef VCENC_QP_TABLES_H
#define VCENC_QP_TABLES_H

#include <stdint.h>

#define VCENC_F_I_LO (2)
#define VCENC_F_I_HI (35)
static const uint32_t VCENC_F_I[VCENC_F_I_HI - VCENC_F_I_LO + 1] = {
	0x00480100, /* q=2   obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x00500120, /* q=3   P-table obs vendor-diff-20260904/E2/vendor_fixqp16_P.txt */
	0x005c0140, /* q=4   obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x00640170, /* q=5   obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x00740190, /* q=6   obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x008001d0, /* q=7   obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x00900200, /* q=8   obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x00a00240, /* q=9   obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x00b40280, /* q=10  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x00cc02d0, /* q=11  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x00e40330, /* q=12  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x01000390, /* q=13  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x01200400, /* q=14  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x01440480, /* q=15  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x016c0510, /* q=16  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x019805b0, /* q=17  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x01c80660, /* q=18  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x02000720, /* q=19  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x02400800, /* q=20  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x02880900, /* q=21  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x02d80a20, /* q=22  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x03300b60, /* q=23  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x03940cc0, /* q=24  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x04040e50, /* q=25  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x04801010, /* q=26  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x05101200, /* q=27  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x05ac1440, /* q=28  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x066016b0, /* q=29  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x07281980, /* q=30  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x08081ca0, /* q=31  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x09042020, /* q=32  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x0a1c2410, /* q=33  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
	0x0b5c2880, /* q=34  interpolated */
	0x0cc02d70, /* q=35  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
};

#define VCENC_F_P_LO (-1)
#define VCENC_F_P_HI (32)
static const uint32_t VCENC_F_P[VCENC_F_P_HI - VCENC_F_P_LO + 1] = {
	0x003400b0, /* q=-1  obs vendor-diff-20260904/E2/vendor_fixqp16_P.txt */
	0x003800c0, /* q=0   interpolated */
	0x004000e0, /* q=1   obs vendor-diff-20260904/E2/vendor_fixqp16_P.txt */
	0x00480100, /* q=2   I-table obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x00500120, /* q=3   obs vendor-diff-20260904/E2/vendor_fixqp16_P.txt */
	0x005c0140, /* q=4   I-table obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x00640170, /* q=5   obs geom-probe/programs/vendor_640x480_P.txt */
	0x00740190, /* q=6   I-table obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x008001d0, /* q=7   obs geom-probe/programs/vendor_640x480_P.txt */
	0x00900200, /* q=8   obs geom-probe/programs/vendor_1024x768_P.txt */
	0x00a00240, /* q=9   obs geom-probe/programs/vendor_640x480_P.txt */
	0x00b40280, /* q=10  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x00cc02d0, /* q=11  obs geom-probe/programs/vendor_640x480_P.txt */
	0x00e40330, /* q=12  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x01000390, /* q=13  obs geom-probe/programs/vendor_640x480_P.txt */
	0x01200400, /* q=14  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x01440480, /* q=15  obs geom-probe/programs/vendor_640x480_P.txt */
	0x016c0510, /* q=16  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x019805b0, /* q=17  obs geom-probe/programs/vendor_640x480_P.txt */
	0x01c80660, /* q=18  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x02040720, /* q=19  obs geom-probe/programs/vendor_640x480_P.txt */
	0x02400810, /* q=20  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x02880900, /* q=21  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x02d80a20, /* q=22  obs geom-probe/programs/vendor_1024x768_P.txt */
	0x03300b60, /* q=23  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x03940cc0, /* q=24  obs geom-probe/programs/vendor_1152x864_P.txt */
	0x04040e50, /* q=25  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x04801010, /* q=26  obs geom-probe/programs/vendor_1152x864_P.txt */
	0x05101200, /* q=27  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x05ac1440, /* q=28  obs geom-probe/programs/vendor_1152x864_P.txt */
	0x066016b0, /* q=29  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x07281980, /* q=30  obs geom-probe/programs/vendor_1152x864_P.txt */
	0x08081ca0, /* q=31  obs vendor-diff-20260904/E2/vendor_fixqp_i28_p34_P.txt */
	0x09042020, /* q=32  obs geom-probe/programs/vendor_1152x864_P.txt */
};

#define VCENC_L_LO (13)
#define VCENC_L_HI (35)
static const uint32_t VCENC_L[VCENC_L_HI - VCENC_L_LO + 1] = {
	0x00000010, /* q=13  obs vendor-diff-20260904/E2/vendor_fixqp16_P.txt */
	0x00000010, /* q=14  interpolated */
	0x00040020, /* q=15  interpolated */
	0x00040020, /* q=16  obs vendor-diff-20260904/E2/vendor_fixqp16_IDR.txt */
	0x00040020, /* q=17  obs vendor-diff-20260904/E2/vendor_fixqp20_P.txt */
	0x00080030, /* q=18  interpolated */
	0x000c0040, /* q=19  obs geom-probe/programs/vendor_640x480_IDR.txt */
	0x000c0050, /* q=20  obs vendor-diff-20260904/E2/vendor_fixqp20_IDR.txt */
	0x00100060, /* q=21  obs vendor-diff-20260904/E2/vendor_fixqp24_P.txt */
	0x00180080, /* q=22  obs geom-probe/programs/vendor_1024x768_IDR.txt */
	0x001c00a0, /* q=23  interpolated */
	0x002400c0, /* q=24  obs vendor-diff-20260904/E2/vendor_fixqp24_IDR.txt */
	0x00300100, /* q=25  obs vendor-diff-20260904/E2/vendor_fixqp28_P.txt */
	0x003c0140, /* q=26  derived g(F(4)) */
	0x004c0190, /* q=27  obs vendor-diff-20260904/E4/vendor_firstqp30_IDR.txt */
	0x00600200, /* q=28  obs vendor-diff-20260904/E2/vendor_fixqp28_IDR.txt */
	0x00780280, /* q=29  obs vendor-diff-20260904/E1/vendor_rc_avbr_P.txt */
	0x00980330, /* q=30  obs vendor-diff-20260904/E4/vendor_iqd_m5_IDR.txt */
	0x00c00400, /* q=31  obs vendor-diff-20260904/E2/vendor_fixqp_i28_p34_P.txt */
	0x00f00510, /* q=32  obs geom-probe/programs/vendor_1152x864_IDR.txt */
	0x01300660, /* q=33  derived g(F(18)) */
	0x01800800, /* q=34  derived g(F(20)) */
	0x01e40a20, /* q=35  obs geom-probe/programs/vendor_1920x1200_IDR.txt */
};

#endif /* VCENC_QP_TABLES_H */
