# NanoKVM-Pro -- mainline U-Boot rung 2 (#89)
DEFAULT nixos
TIMEOUT 10
MENU TITLE NanoKVM-Pro (mainline chain)

LABEL nixos
	MENU LABEL NixOS appliance, mainline 7.1.3
	LINUX /Image
	FDT /ax630c-nanokvm-pro.dtb
	APPEND mem=512M console=ttyS0,115200n8 earlycon=uart8250,mmio32,0x4880000 board_id=0x5,boot_reason=0x04,initcall_debug=0 loglevel=8 usbcore.autosuspend=-1 root=/dev/mmcblk0p17 rootfstype=ext4 rw rootwait blkdevparts=mmcblk0:768K(spl),512K(ddrinit),256K(atf),256K(atf_b),1536K(uboot),1536K(uboot_b),1M(env),6M(logo),6M(logo_b),1M(optee),1M(optee_b),1M(dtb),1M(dtb_b),64M(kernel),64M(kernel_b),128M(boot),-(rootfs) logomode=vo0@dsi_dpi_video
