#!/usr/bin/env python3
"""gen_font.py -- BUILD-TIME tool (runs on the Nix build host, never on device).

Converts PSF2 console fonts (e.g. nixpkgs' source-built terminus_font
ter-u16n.psf.gz / ter-u28b.psf.gz) into a plain-Python module `font_data.py`
embedded next to the on-device daemon. This keeps the shipped image free of
any font *parsing* at runtime and -- more importantly -- free of any new
binary asset: the glyphs come from a package nixpkgs builds from source.

Usage:  gen_font.py OUT.py NAME=path/to/font.psf.gz [NAME2=...]

Output module shape (pure literals, no imports):
    FONTS = {
      "NAME": {"w": 8, "h": 16, "glyphs": { ord(ch): bytes(rowbytes...) }},
      ...
    }
Each glyph is `h * bytes_per_row` bytes, MSB-first per row (PSF bit order).
Only ASCII 32..126 is emitted -- all the status daemon needs.
"""
import gzip
import struct
import sys

PSF2_MAGIC = 0x864AB572
PSF2_HAS_UNICODE_TABLE = 0x01
PSF1_MAGIC = 0x0436
PSF1_MODEHASTAB = 0x02


def load_psf1(raw, path):
    """PSF1: 4-byte header (magic16, mode8, charsize8); width fixed at 8."""
    magic, mode, charsize = struct.unpack("<HBB", raw[:4])
    length = 512 if (mode & 0x01) else 256
    glyph_data = raw[4:4 + length * charsize]
    glyphs = [glyph_data[i * charsize:(i + 1) * charsize] for i in range(length)]

    cp_to_glyph = {}
    if mode & PSF1_MODEHASTAB:
        # per glyph: UCS-2 LE codepoints, 0xFFFE starts combining seqs (skip),
        # 0xFFFF terminates the entry.
        table = raw[4 + length * charsize:]
        vals = struct.unpack(f"<{len(table) // 2}H", table[:len(table) // 2 * 2])
        gi, skipping = 0, False
        for v in vals:
            if v == 0xFFFF:
                gi += 1
                skipping = False
            elif v == 0xFFFE:
                skipping = True
            elif not skipping and gi < length:
                cp_to_glyph.setdefault(v, gi)
    else:
        for cp in range(min(length, 127)):
            cp_to_glyph[cp] = cp
    return 8, charsize, glyphs, cp_to_glyph


def load_psf2(path):
    raw = open(path, "rb").read()
    if path.endswith(".gz") or raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)

    if struct.unpack("<H", raw[:2])[0] == PSF1_MAGIC:
        return load_psf1(raw, path)

    (magic, version, headersize, flags,
     length, charsize, height, width) = struct.unpack("<8I", raw[:32])
    if magic != PSF2_MAGIC:
        raise SystemExit(f"{path}: not a PSF1/PSF2 font (magic {magic:#x})")

    glyph_data = raw[headersize:headersize + length * charsize]
    glyphs = [glyph_data[i * charsize:(i + 1) * charsize] for i in range(length)]

    # Unicode table: for each glyph, UTF-8 codepoint sequences terminated by
    # 0xFF (0xFE starts combining sequences -- we ignore those).
    cp_to_glyph = {}
    if flags & PSF2_HAS_UNICODE_TABLE:
        table = raw[headersize + length * charsize:]
        gi, i = 0, 0
        entry = bytearray()
        while i < len(table) and gi < length:
            b = table[i]
            if b == 0xFF:  # end of this glyph's entry
                for ch in entry.decode("utf-8", "ignore"):
                    cp_to_glyph.setdefault(ord(ch), gi)
                entry = bytearray()
                gi += 1
            elif b == 0xFE:  # combining sequences follow; skip to 0xFF
                for ch in entry.decode("utf-8", "ignore"):
                    cp_to_glyph.setdefault(ord(ch), gi)
                entry = bytearray()
                while i < len(table) and table[i] != 0xFF:
                    i += 1
                continue  # let the 0xFF branch close the entry
            else:
                entry.append(b)
            i += 1
    else:  # no table: assume glyph index == codepoint (cp437-ish; good enough for ASCII)
        for cp in range(min(length, 127)):
            cp_to_glyph[cp] = cp

    return width, height, glyphs, cp_to_glyph


def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__)
    out_path = sys.argv[1]

    lines = ["# Generated by gen_font.py at build time -- do not edit.",
             "# Glyphs converted from source-built PSF2 console fonts (see gen_font.py).",
             "FONTS = {"]
    for spec in sys.argv[2:]:
        name, _, path = spec.partition("=")
        w, h, glyphs, cp_map = load_psf2(path)
        lines.append(f'    "{name}": {{"w": {w}, "h": {h}, "glyphs": {{')
        for cp in range(32, 127):
            gi = cp_map.get(cp)
            if gi is None:
                continue
            lines.append(f"        {cp}: {bytes(glyphs[gi])!r},")
        lines.append("    }},")
    lines.append("}")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}: {', '.join(s.partition('=')[0] for s in sys.argv[2:])}")


if __name__ == "__main__":
    main()
