import struct, glob, os, re, collections
D=os.path.dirname(os.path.abspath(__file__))+"/device"; REF="/home/googlebot/workspace/nanokvm/nix-nanokvm-pro/docs/reference/deblob-scope/regdumps/frontend"
def load(p):
    b=open(p,"rb").read(); return list(struct.unpack("<%dI"%(len(b)//4),b))
def dump(tag,stage,bank): 
    p=f"{D}/{tag}-{stage}-{bank}.bin"; return load(p) if os.path.exists(p) else None
out=[]
def W(s=""): out.append(s)
# ---------- generic per-word diff table ----------
def table(title, runs, bank, stage="start", note=""):
    W(f"### {title}\n"); W(f"Bank `0x{bank}`, stage `{stage}` (dump files `<tag>-{stage}-{bank}.bin`). {note}\n")
    data={t:dump(t,stage,bank) for t in runs}; data={t:v for t,v in data.items() if v}
    tags=list(data); n=len(data[tags[0]])
    varying=[i for i in range(n) if len({data[t][i] for t in tags})>1]
    # live/counter words: differ between start and start2 in the same run
    live=set()
    for t in tags:
        s2=dump(t,"start2",bank)
        if s2: live|={i for i in range(n) if s2[i]!=data[t][i]}
    W(f"Words present: {n}; words differing across runs: {len(varying)}; of those, words that also change between two dumps of the SAME run (live status/counters): {len([i for i in varying if i in live])}.\n")
    if not varying: W("**No word differs across these runs.**\n"); return
    W("| offset | "+" | ".join(tags)+" | live? |"); W("|---|"+"---|"*(len(tags)+1))
    for i in varying: W(f"| +0x{i*4:04x} | "+" | ".join(f"{data[t][i]:08x}" for t in tags)+f" | {'yes' if i in live else 'NO'} |")
    W("")
    stable=[i for i in varying if i not in live]
    if stable: W("Non-live words that differ: "+", ".join(f"+0x{i*4:04x}" for i in stable)+"\n")
    else: W("**Every differing word is a live status/counter word (changes between two dumps of one run); no configuration word depends on the parameter.**\n")
# ---------- M4 ----------
W("# Per-word diff tables (generated by analyze.py from device/ dumps)\n")
W("## M4 DataRate sweep (4 lanes, MODE_0)\n")
rates=["L4R80","L4R200","L4R400","L4R600","L4R800","L4R1000","L4R1200","L4R1500","L4R2500","L4R600b"]
table("M4 D-PHY 0x023f0000 vs nDataRate", rates, "023f0000")
table("M4 CSI-2 controller 0x02600000 vs nDataRate", rates, "02600000")
table("M4 isp_sys_glb 0x02500000 vs nDataRate", rates, "02500000")
table("M4 common_glb 0x02340000 vs nDataRate", rates, "02340000")
# ---------- M5 ----------
W("## M5 LaneNum sweep (DataRate 600)\n")
lanes=["L1R600","L2R600","L3R600","L4R600","V_L2C1","V_L1C2","V_L4C1","V_L2rst","P_L1ord","P_L2ord","P_L2C1"]
W("| run | LaneNum | combo | order | csi +0x40 (N_LANES) | csi +0x100 | dphy +0x34 mirror | glb +0x00 |"); W("|---|---|---|---|---|---|---|---|")
for t in lanes:
    txt=open(f"{D}/{t}.txt").read(); m=re.search(r"lanes=(\d+) rate=\d+ reset=\d combo=(\d)",txt); o="SetAttr first" if "after SetAttr" in txt else "SetLaneCombo first"
    d=dump(t,"start","02600000"); p=dump(t,"start","023f0000"); g=dump(t,"start","02500000")
    W(f"| {t} | {m.group(1)} | MODE_{m.group(2)} | {o} | {d[0x40//4]:08x} | {d[0x100//4]:08x} | {p[0x34//4]:08x} | {g[0]:08x} |")
W("")
table("M5 CSI-2 controller 0x02600000 vs LaneNum (MODE_0 runs)", ["L1R600","L2R600","L3R600","L4R600","L4R600b"], "02600000")
table("M5 D-PHY 0x023f0000 vs LaneNum (MODE_0 runs)", ["L1R600","L2R600","L3R600","L4R600","L4R600b"], "023f0000")
table("M5 D-PHY 0x023f0000 vs LaneCombo (MODE_0 vs MODE_1 vs MODE_2)", ["L4R600","V_L4C1","V_L2C1","V_L1C2"], "023f0000")
table("M5 CSI-2 0x02600000 vs LaneCombo", ["L4R600","V_L4C1","V_L2C1","V_L1C2"], "02600000")
# ---------- reference check ----------
W("## API-driven state vs the real vendor KVM streaming dumps (regdumps/frontend/vendor-streaming-*)\n")
for bank in ["02600000","023f0000","02500000","02340000"]:
    a=dump("L4R600","start",bank); b=load(f"{REF}/vendor-streaming-{bank}.bin")
    diff=[i for i in range(min(len(a),len(b))) if a[i]!=b[i]]
    W(f"- `0x{bank}`: {len(diff)} words differ between L4R600-start and vendor-streaming"+(": "+", ".join(f"+0x{i*4:x}({b[i]:x}->{a[i]:x})" for i in diff[:40]) if diff else "")+("" if len(diff)<=40 else " ..."))
W("")
# ---------- M6 ----------
W("## M6 stream-control semantics (poll logs: `<tag>-poll.txt`, tight-loop transitions)\n")
for t in ["P_L4","P_L4rst","P_L1ord","P_L2ord","P_L2C1"]:
    p=f"{D}/{t}-poll.txt"
    if not os.path.exists(p): continue
    rows=[l.split() for l in open(p) if not l.startswith("#")]
    hdr=[l for l in open(p) if l.startswith("# t_us")][0].split()[2:]
    idx={n:i for i,n in enumerate(hdr)}
    keep=["csi+04","csi+40","csi+50","csi+100","csi+110","csi+118","dphy+34","dphy+110","glb+00","csi+2c"]
    W(f"### {t}\n"); W("| t_us | "+" | ".join(keep)+" |"); W("|---|"+"---|"*len(keep))
    prev=None; err=collections.Counter(); err1=collections.Counter()
    for r in rows:
        v=tuple(r[1+idx[k]] for k in keep); err[r[1+idx["csi+28"]]]+=1; err1[r[1+idx["csi+4c"]]]+=1
        if v!=prev: W(f"| {float(r[0]):.1f} | "+" | ".join(v)+" |"); prev=v
    W(""); W(f"csi+0x28 (ErrorStatus0) values seen in {len(rows)} sampled events: "+", ".join(f"{k}x{c}" for k,c in err.most_common(8)))
    W(f"csi+0x4c (ErrorStatus1) values seen: "+", ".join(f"{k}x{c}" for k,c in err1.most_common(6))+"\n")
    txt=open(f"{D}/{t}.txt").read()
    for st in ["pre","attr","rst","start","start2","stop"]:
        m=re.search(rf"\[{st}\] .*csi\+0x100=(\w+).*glb\+0x00=(\w+) deskew\[1:0\]=(\d).*lt6911 (\S+)",txt)
        if m: W(f"- stage `{st}`: csi+0x100={m.group(1)} glb+0x00={m.group(2)} deskew[1:0]={m.group(3)} lt6911={m.group(4)}")
    W("")
# ---------- M1 link-state per run ----------
W("## M1 link state recorded with every dump\n")
W("| run | stage | lt6911 | glb+0x00 | deskew[1:0] | csi+0x28 | csi+0x4c |"); W("|---|---|---|---|---|---|---|")
for f in sorted(glob.glob(f"{D}/*.txt")):
    t=os.path.basename(f)[:-4]
    if t.endswith("-poll"): continue
    for l in open(f):
        m=re.match(r"\[(\w+)\] .*csi\+0x28=(\w+).*csi\+0x4c=(\w+).*glb\+0x00=(\w+) deskew\[1:0\]=(\d) \| lt6911 (\S+)",l)
        if m and m.group(1) in ("start","stop","pre"): W(f"| {t} | {m.group(1)} | {m.group(6)} | {m.group(4)} | {m.group(5)} | {m.group(2)} | {m.group(3)} |")
open(os.path.dirname(os.path.abspath(__file__))+"/TABLES.md","w").write("\n".join(out)+"\n")
print("\n".join(out)[:12000])
